-- zadanie 1
SELECT
    NR_KONTA,
    TYP,
    KATEGORIA,
    SUM(KWOTA) AS SUM
FROM TRANSAKCJE
GROUP BY GROUPING SETS (
    (NR_KONTA, TYP, KATEGORIA),
    (NR_KONTA, TYP),
    (NR_KONTA),
    ()
)
ORDER BY
    NR_KONTA,
    typ,
    TYP DESC,
    KATEGORIA
;

-- zadanie 2
SELECT
    NR_KONTA,
    TYP,
    SUM(KWOTA) AS SUM
FROM TRANSAKCJE
GROUP BY GROUPING SETS (
    (NR_KONTA, TYP),
    (NR_KONTA)
)
ORDER BY
    NR_KONTA
;

-- zadanie 3
SELECT
    NR_KONTA,
    TYP,
    AVG(KWOTA) AS SREDNIA
FROM TRANSAKCJE
GROUP BY GROUPING SETS (
    (NR_KONTA, TYP),
    (NR_KONTA),
    (TYP),
    ()
)
ORDER BY
    NR_KONTA,
    TYP
;

-- zadanie 4
SELECT
    RANK() OVER (PARTITION BY KATEGORIA ORDER BY KWOTA DESC) AS RANK,
    DENSE_RANK() OVER (PARTITION BY KATEGORIA ORDER BY KWOTA DESC) AS DENSE_RANK,
    KATEGORIA,
    DATA,
    KWOTA
FROM TRANSAKCJE
WHERE NR_KONTA = '11-11111111'
ORDER BY KATEGORIA, KWOTA DESC, DATA
;

-- zadanie 5
SELECT KWOTA, DATA, NR_KONTA
FROM (
    SELECT
        KWOTA,
        DATA,
        NR_KONTA,
        ROW_NUMBER() OVER (ORDER BY KWOTA DESC) AS RN
    FROM TRANSAKCJE
    WHERE KWOTA > 0
) AS SUBQUERY
WHERE RN <= 3
ORDER BY KWOTA DESC
;
